### ISSUE TITLE
.shift

### ISSUE THREAD

**Issue by melissamcewen** [trellbot/teacozy#2]
First of all, good job creating a general class to deal with this - generalization (making a class that applies to a particular design pattern) is one of the hardest CSS skills to master. But one thing I'd like to see here is a name or comment that indicate what this is for since the word `shift` can mean so many different things. In the solution code they have something similar named `flex container`

```css
.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
```
