### ISSUE TITLE
Locations Block

### ISSUE THREAD

**Issue by melissamcewen** [trellbot/teacozy#4]
I noticed in your commit message you said you weren't sure about this. I think it looks good to me, but the spacing is a bit different from the spec. In the solution this how they did it

```html
    <div id="locations">
      <h2>Locations</h2>
      <div class="flex-container locations">
        <div class="location">
          <h3>Downtown</h3>
          <p>384 West 4th St</p>
          <p>Suite 108</p>
          <p>Portland, Maine</p>
        </div>
        <div class="location">
          <h3>East Bayside</h3>
          <p>3433 Phisherman's Avenue</p>
          <p>(Northwest Corner)</p>
          <p>Portland, Maine</p>
        </div>
        <div class="location">
          <h3>Oakdale</h3>
          <p>515 Crescent Avenue</p>
          <p>Second Floor</p>
          <p>Portland, Maine</p>
        </div>
      </div>
    </div>
```

```css
/* Location Section */

.flex-container.locations {
  padding-top: 5px;
}

#locations {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-locations-background.jpg");
  height: 500px;
  padding-top: 70px;
}

#locations .flex-container {
  margin: auto;
  width: 1100px;
}

.location {
  flex-basis: 280px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 10px;
  margin: 5px 20px;
  opacity: 1.0;
  background-color: black;
}

```

it uses the aforementioned `.flex-container` I mentioned in the previous issue
```css
.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
```

One tip is you can use the Chrome Inspector on the project page to see how the solution works
https://www.codecademy.com/courses/freelance1-u4/projects/tea-cozy?program_content_id=103e02e37b36102efba7973dab4b22aa&program_id=bd3bff8ce8ce2f11781cdf436a004629

![flex-container](https://user-images.githubusercontent.com/1251094/39450801-28d2f6b8-4c92-11e8-9e75-e7940f630000.png)

Yours is mostly similar except the solution:
* makes use of `flex-direction: column;` and `flex-basis`
* Doesn't need the hardcoded width - in general try to hardcode (specific height/width) as few things as possible as they can cause issues, especially when dealing with responsive design in the next part of the course
